"""
Shared Excel export helper. Generates a single-sheet workbook from a list
of dict rows with a small identifying header block, matching the format
spec Section 36A asks for on every export ("Export Generated By", "Export
Date/Time", etc.). M25's stage-wise appraisal exports reuse this exact
function; M3/M4 uses it first for master-data snapshots (Section 6).
"""
import io
from datetime import datetime, timezone

from openpyxl import Workbook
from openpyxl.styles import Font
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet


def build_export_workbook(
    *,
    sheet_title: str,
    headers: list[str],
    rows: list[list],
    generated_by: str,
    context_label: str,
    filter_criteria: str = "None",
) -> bytes:
    wb = Workbook()
    ws: Worksheet = wb.active
    ws.title = sheet_title[:31]  # Excel sheet name limit

    ws.append([f"Export Generated By: {generated_by}"])
    ws.append([f"Export Date/Time: {datetime.now(timezone.utc).isoformat()}"])
    ws.append([f"Context: {context_label}"])
    ws.append([f"Filter Criteria Applied: {filter_criteria}"])
    ws.append([])

    header_row_idx = ws.max_row + 1
    ws.append(headers)
    for row in rows:
        ws.append(row)

    # Font.copy(bold=True) is deprecated in current openpyxl - build a new
    # Font explicitly instead of mutating a copy of the existing one.
    for col_idx in range(1, len(headers) + 1):
        ws.cell(row=header_row_idx, column=col_idx).font = Font(bold=True)

    ws.freeze_panes = ws.cell(row=header_row_idx + 1, column=1)
    ws.auto_filter.ref = (
        f"A{header_row_idx}:{get_column_letter(len(headers))}{ws.max_row}"
    )
    for col_idx, header in enumerate(headers, start=1):
        max_len = max([len(header)] + [len(str(r[col_idx - 1])) for r in rows]) if rows else len(header)
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 4, 60)

    buffer = io.BytesIO()
    wb.save(buffer)
    return buffer.getvalue()
